### ISSUE TITLE
Possible race condition ?

### ISSUE THREAD

**Issue by jetacpp** [kanflo/opendps#140]
Hello,
I was going through the code and wondered the followings:

1. the event ring buffer is not protected by mutex. Even though the risk of data corruption is low due to slow button presses and uart. 
2. In the main loop event handler, it implied that it should not receive event_none (dbg_printf("Weird, should not receive 'none events'\n");). Why is so ? as I searched and the only sources to feed the event buffer are button presses and uart. Obviously the even buffer will be empty most of the time, won't it ?
3. hw_get_adc_value() routine is at high risk of data corruption due to high ADC sampling. Writing in /reading out uint16_t adc values are not atomic on this MCU. Have you experienced data display corruption at all ?

**Comment by kanflo** [comment]
Hi @jetacpp and thanks for your comments!

1. I implemented the ring buffer as a circular buffer for one writer and one reader. ISRs write and user code reads without affecting each others unless the buffer is close to being filled which should not happen:

https://github.com/kanflo/opendps/blob/4f227ecafdd6ecc8b1889dd4688cee899e5f082c/opendps/ringbuf.c#L57

2. At one point I received 'None' events so I added this but have not seen it since.

3. That I did not know, thanks for the heads up. I will look into it.
