### ISSUE TITLE
Disable button doesn't work in my DPS3003 with CC firmware

### ISSUE THREAD

**Issue by splasma** [kanflo/opendps#15]
Hi, first at all, great work !!
After burned the CC firmware in my "small" DPS3003 the enable/disable button does not  disconnect the output, the voltage is  getting out always :-( ...

**Comment by kanflo** [comment]
Thanks! I recall this was a problem with the newer comms versions of the DPS5005, but got fixed in [this](https://github.com/kanflo/opendps/commit/5d2e74b90c973e079a509b304c4f636599f78d8f) commit. You did not by any chance run [ocd-client.py](https://github.com/kanflo/opendps/blob/master/ocd-client.py) before flashing as described under ["Please note" here](https://johan.kanflo.com/upgrading-your-dps5005/)? Chances are the hardware changed meaning the disabling sequence needs trimming.

**Comment by splasma** [comment]
Uhh, I didn't run ocd-client.py before flashing... as you recommended (!),
next time :-)
Anyway, with the "master branch" firmware ( no CC) works perfectly.
thanks for the quick reply.

2017-10-06 13:40 GMT+02:00 Johan Kanflo <notifications@github.com>:

**Comment by kanflo** [comment]
I guess I should modify ```make flash``` to ask if ocd-client.py has been run :)

**Comment by splasma** [comment]
:-) good idea ! for impatient people...

2017-10-17 15:52 GMT+02:00 Johan Kanflo <notifications@github.com>:
