### ISSUE TITLE
Force Voltage calibration line of best fits to pass through (0, 0)

### ISSUE THREAD

**Issue by Xenoamor** [kanflo/opendps#158]
Very low current and voltage calibration seems a little off.

I propose we assume that the voltage plots pass through the (0, 0) point and force the line of best fit to also do the same. As you can see the below line of best fit misses this
![image](https://user-images.githubusercontent.com/7109951/64774990-261acf00-d54d-11e9-9d70-dfd02ed75512.png)
This should help the low end performance (assuming all hardware models act the same)

As this may potentially skew the top end I propose we add another couple of measurement points from the user

**Comment by danielkucera** [comment]
My proposal is to measure user defined number of voltages/currents with minimum of two (0V and 90% of input voltage). Then do linear regression to find the coefficients. 

At the end measure zeroes again and ask if user desires to adjust the zero offset. 

It might also be better to use ampermeter to measure current (or at least to provide the option) because resistance of a resistor might change during measurement due to it can heating up.

**Comment by JackNewman12** [comment]
If you only do two points with one at 0V. Then you are guaranteed to get a good zero offset. No need to remeasure it. 

Good point about the resistor. (I think we should make a seperate ticket for current measurements?)

While we are doing the voltage calibration we should also measure the 0 current point, since the user does not have a load connected at this stage.

**Comment by danielkucera** [comment]
> If you only do two points with one at 0V. Then you are guaranteed to get a good zero offset. No need to remeasure it.

Yes but if you do more than two then no.

**Comment by Xenoamor** [comment]
Once this is implemented the 0 current measurement as discussed in #130 should also be resolved. This is because the current calibration assumes that setting the output voltage to 0V does indeed disable the output (which it would after this change)

**Comment by Xenoamor** [comment]
Okay I was wrong about this resolving the open circuit current reading. It's a step in the right direction but we need to force the following graph to pass through the y=0 reading:
![image](https://user-images.githubusercontent.com/7109951/65379557-f2187a00-dcc1-11e9-937f-8e0cd6d4e02d.png)

**Comment by kanflo** [comment]
Just curious, why does the I(A_ADC) line need to pass (0, 0)? I guess in a perfect world it should but your measurements are consistent with [my original measurements](https://docs.google.com/spreadsheets/d/1AhGsU_gvZjqZyr2ZYrnkz6BeUqMquzh9UNYoTqy_Zp4/edit#gid=144499878):

![Screenshot 2019-10-02 at 20 01 45](https://user-images.githubusercontent.com/931076/66069396-94045600-e54f-11e9-8a74-55d54300021c.png)

**Comment by Xenoamor** [comment]
The issue currently is that the line doesn't pass through the y = 0 reading which means that even when there is no current flowing the device often still reports some. It's a tradeoff though, the top end will become less accurate

**Comment by kanflo** [comment]
That could be written off as "this is a cheap power supply, don't expect National Instruments accuracy" ;)

**Comment by Xenoamor** [comment]
Yeah that's definitely my understanding. I'd rather it be more accurate across the entire range personally

**Comment by kanflo** [comment]
I totally agree.

**Comment by Xenoamor** [comment]
Should probably reverse the commit. It's also more likely to work across every device without it

**Comment by kanflo** [comment]
Done, with the added benefit of increasing my git knowhow.
