### ISSUE TITLE
Could this firmware also work on the step-up/boost DPH models?

### ISSUE THREAD

**Issue by clickworkorange** [kanflo/opendps#21]
They use the same front-panel, and are probably quite similar on the controller side, though the DC/DC converter is on a separate board. I guess it's unlikely, but maybe I can retrace the steps taken and try to identify where they differ? I'm in need of a couple of boost capable PSUs for a 12V electrical system, but am severely put off by the cluttered and clunky stock UI - I would only buy them if there's a decent chance of success with performing this firmware replacement.

**Comment by kanflo** [comment]
I would guess it works but there is only one way to find out ;) Since both models offer the same functionality I'd be surprised if the STM32 interfaces weren't identical with respect to buttons, DAC control and so on. [My blog post](https://johan.kanflo.com/hacking-the-dps5005/) on reverse engineering the DPS5015 describes the steps for learning how the stock FW talks to the HW.
